function action(){
            var ok=confirm("Etes-vous sur de vouloir quitter cette page???");
if (ok)
{alert("Allons-y");
return true;
}
else
{alert("abandon");
return false;}
}

function bienvenue1() {
alert("BIENVENUE SUR LA PAGE D'ACCUEIL!!!");
}

function bienvenue2() {
alert("BIENVENUE SUR LA PAGE MARQUE!!!");
}

function bienvenue3() {
alert("BIENVENUE SUR LA PAGE CONTACT !!!");
}

function bienvenue4() {
alert("BIENVENUE SUR LA PAGE COMMANDER !!!");
}

function bienvenue5() {
alert("BIENVENUE SUR LA PAGE MODIFIER UNE COMMANDE DEJA LANCEE !!!");
}

function bienvenue6() {
alert("BIENVENUE SUR LA PAGE NOS DIFFERENT MARQUE DE VOITURE !!!");
}


